var test trials = [
{"trial_id": "brush_WE",
"video": "videos/BrushTest.mp4",
"target_pic": "images/instruments/Brush1.png",
"foil_pic": "images/substances/BlueSand.png",
"trial_type": "critical",
"question_length": "26050",
},
{"trial_id": "rake_WE",
"video": "videos/RakeTest.mp4",
"target_pic": "images/instruments/GreenRake2.png",
"foil_pic": "images/substances/GreenPotpourri3.png",
"trial_type": "critical",
"question_length": "24700",
},
{"trial_id": "shovel_WE",
"video": "videos/ShovelTest.mp4",
"target_pic": "images/instruments/YellowShovel.png",
"foil_pic": "images/substances/Dirt2.png",
"trial_type": "critical",
"question_length": "26040",
},
{"trial_id": "scoop_WE",
"video": "videos/ScoopTest.mp4",
"target_pic": "images/instruments/Scoop.png",
"foil_pic": "images/substances/GroundCoffee1.png",
"trial_type": "critical",
"question_length": "26040",
},
{"trial_id": "hammer_WE",
"video": "videos/HammerTest1s.mp4",
"target_pic": "images/instruments/Hammer.png",
"foil_pic": "images/substances/PinkPutty2.png",
"trial_type": "critical",
"question_length": "26660",
},
];

var training_trials = [
{"trial_id": "ball_WE",
"video": "videos/Ball.mp4",
"target_pic": "images/warmupimages/YellowBall.png",
"foil_pic": "images/warmupimages/BlueChair.png",
"trial_type": "training",
"question_length": "7800”,
},
{"trial_id": "book_WE_feedback",
"video": "videos/Book.mp4",
"target_pic": "images/warmupimages/RedBook.png",
"foil_pic": "images/warmupimages/BlueChair.png",
"trial_type": "training",
"question_length": "9040",
},
{"trial_id": "intro",
"video": "videos/Intro.mp4",
"target_pic": "images/warmupimages/HappyFace3.png",
"foil_pic": "images/warmupimages/SadFace.png",
"trial_type": "training",
"question_length": "10300",
},
];

var filler_trials = [
{"trial_id": "cup_WE",
"video": "videos/Cup.mp4",
"target_pic": "images/warmupimages/PolkaDotCup.png",
"foil_pic": "images/warmupimages/PinkTable.png",
"trial_type": "training",
"question_length": "7640”,
},
{"trial_id": "shoe_WE",
"video": "videos/Shoe.mp4",
"target_pic": "images/warmupimages/BlueShoe.png",
"foil_pic": "images/warmupimages/GreenApple.png",
"trial_type": "training",
"question_length": "8560”,
},];