var trials = [
{"trial_id": "brush_WE",
"video": "videos/brush_lo.mp4",
"target_pic": "images/instruments/Brush1.png",
"foil_pic": "images/substances/BlueSand.png",
"trial_type": "critical",
"question_length": "26.050",
},
{"trial_id": "rake_WE",
"video": "videos/rake_lo.mp4",
"target_pic": "images/instruments/GreenRake2.png",
"foil_pic": "images/substances/GreenPotpourri3.jpg",
"trial_type": "critical",
"question_length": "24.700",
},
{"trial_id": "shovel_WE",
"video": "videos/shovel_lo.mp4",
"target_pic": "images/instruments/YellowShovel.png",
"foil_pic": "images/substances/Dirt2.png",
"trial_type": "critical",
"question_length": "26.040",
},
{"trial_id": "scoop_WE",
"video": "videos/scoop_lo.mp4",
"target_pic": "images/instruments/Scoop.png",
"foil_pic": "images/substances/GroundCoffee1.png",
"trial_type": "critical",
"question_length": "26.040",
},
{"trial_id": "hammer_WE",
"video": "videos/hammer_lo.mp4",
"target_pic": "images/instruments/Hammer.png",
"foil_pic": "images/substances/PinkPutty2.png",
"trial_type": "critical",
"question_length": "26.660",
},
];

var training_trials = [
{"trial_id": "ball_WE",
"video": "videos/ball_lo.mp4",
"target_pic": "images/warmupimages/RedBall.png",
"foil_pic": "images/warmupimages/BlueHat.png",
"trial_type": "training",
"question_length": "7.800",
},
{"trial_id": "book_WE_feedback",
"video": "videos/book_lo.mp4",
"target_pic": "images/warmupimages/RedBook.png",
"foil_pic": "images/warmupimages/BlueChair.png",
"trial_type": "training",
"question_length": "9.040",
},
{"trial_id": "intro",
"video": "videos/intro1_lo.mp4",
"target_pic": "images/warmupimages/HappyFace3.png",
"foil_pic": "images/warmupimages/SadFace.png",
"trial_type": "training",
"question_length": "11.300",
},
];

var filler_trials = [
{"trial_id": "cup_WE",
"video": "videos/cup_lo.mp4",
"target_pic": "images/warmupimages/PolkaDotCup.png",
"foil_pic": "images/warmupimages/PinkTable.png",
"trial_type": "filler",
"question_length": "7.640",
},
{"trial_id": "shoe_WE",
"video": "videos/shoe_lo.mp4",
"target_pic": "images/warmupimages/BlueShoe.png",
"foil_pic": "images/warmupimages/GreenApple.png",
"trial_type": "filler",
"question_length": "8.560",
},];