var trials = [
	{"trial_id": "brush_WE",
		"video": "videos/brush_lo.mp4",
		"target_pic": "images/instruments/Brush1.png",
		"foil_pic": "images/substances/BlueSand.jpg",
		"trial_type": "critical",
		"question_length": "27000",
	},
	{"trial_id": "rake_WE",
		"video": "videos/rake_lo.mp4",
		"target_pic": "images/instruments/Rake1.png",
		"foil_pic": "images/substances/GreenPotpourri3.jpg",
		"trial_type": "critical",
		"question_length": "26000",
	},
	{"trial_id": "shovel_WE",
		"video": "videos/shovel_lo.mp4",
		"target_pic": "images/instruments/Shovel1.png",
		"foil_pic": "images/substances/Dirt1.jpg",
		"trial_type": "critical",
		"question_length": "28000",
	},
	{"trial_id": "scoop_WE",
		"video": "videos/scoop_lo.mp4",
		"target_pic": "images/instruments/Scoop1.png",
		"foil_pic": "images/substances/GroundCoffee1.jpg",
		"trial_type": "critical",
		"question_length": "26000",
	},
	];

var training_trials = [
	{"trial_id": "apple_WE",
		"video": "videos/intro_lo.mp4",
		"target_pic": "images/warmupimages/apple.jpg",
		"foil_pic": "images/warmupimages/table.jpg",
		"trial_type": "training",
		"question_length": "13000",
	},
	{"trial_id": "cup_WE",
		"video": "videos/intro_lo.mp4",
		"target_pic": "images/warmupimages/bluecup.jpg",
		"foil_pic": "images/warmupimages/sportyshoe.jpg",
		"trial_type": "training",
		"question_length": "13000",
	},
	{"trial_id": "shoe_WE",
		"video": "videos/intro_lo.mp4",
		"target_pic": "images/warmupimages/blueshoe.jpg",
		"foil_pic": "images/warmupimages/polkadotcup.jpg",
		"trial_type": "training",
		"question_length": "13000",
	},
	{"trial_id": "book_WE",
		"video": "videos/intro_lo.mp4",
		"target_pic": "images/warmupimages/book.jpeg",
		"foil_pic": "images/warmupimages/kidschair.jpg",
		"trial_type": "training",
		"question_length": "13000",
	},
	{"trial_id": "intro",
		"video": "videos/intro_lo.mp4",
		"target_pic": "images/dots/dot_smiley.jpg",
		"foil_pic": "images/dots/dot_1.png",
		"trial_type": "training",
		"question_length": "13000",
	},
];